name: Deploy with ansible 

on:
  push:
    branches: [ master]  # Trigger when code is pushed to main branch
  workflow_dispatch:     # Allows you to run manually from the Actions tab

jobs:
  ansible_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ansible repo
        uses: actions/checkout@v3
        with:
          repository:  BhavadharaniM-007/deployment-ansible
          ref: master
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa_github_actions_new
          chmod 600 ~/.ssh/id_rsa_github_actions_new 
      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H 3.239.216.100 >> ~/.ssh/known_hosts
          ssh-keyscan -H 13.220.33.232 >> ~/.ssh/known_hosts          
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ansibleconfig/inventory.ini ansibleconfig/playbook.yml --private-key /home/runner/.ssh/id_rsa_github_actions_new
        # Use secrets to provide SSH keys if needed
