name: Deploy with Ansible

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  ansible_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ansible repo
        uses: actions/checkout@v3
        with:
          repository: BhavadharaniM-007/deployment-ansible
          ref: master

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa_github_actions_new
          chmod 600 ~/.ssh/id_rsa_github_actions_new

      - name: Generate dynamic inventory.ini
        run: |
          echo "[app]" > ansibleconfig/inventory.ini
          echo "${{ secrets.EC2_PUBLIC_IP_1 }} ansible_user=ec2-user ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa_github_actions_new" >> ansibleconfig/inventory.ini
          echo "${{ secrets.EC2_PUBLIC_IP_2 }} ansible_user=ubuntu ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa_github_actions_new" >> ansibleconfig/inventory.ini

      - name: Add EC2 instances to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP_1 }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP_2 }} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ansibleconfig/inventory.ini ansibleconfig/playbook.yml --private-key /home/runner/.ssh/id_rsa_github_actions_new
